[tool.ruff]
line-length = 120
target-version = "py311"
select = ["E", "F", "W", "I"]
ignore = [
  # Allow long lines for HA logging/messages
  "E501",
]
exclude = [
  ".git",
  ".github",
  "__pycache__",
  "build",
  "dist",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"